services:
  # Portfolio Application
  portfolio-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-app
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT:-3000}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:${PORT:-3000}/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Prisma Studio (Optional - for database management)
  prisma-studio:
    image: node:24-alpine
    container_name: portfolio-prisma-studio
    working_dir: /app
    command: >
      sh -c "
        npm install -g prisma &&
        prisma studio --hostname 0.0.0.0 --port 5555
      "
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "5555:5555"
    profiles:
      - tools

networks:
  portfolio-network:
    driver: bridge
