/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./app/**/*.{js,ts,jsx,tsx}",
    "./app/components/**/*.{js,ts,jsx,tsx}",
    "./app/routes/**/*.{js,ts,jsx,tsx}",
    "./app/lib/**/*.{js,ts,jsx,tsx}"
  ],
  theme: {
    extend: {
      colors: {
        // Add any custom colors you want to extend
      },
      fontFamily: {
        // Add any custom fonts
      },
    },
  },
  plugins: [],
  // Ensure all CSS is included in production builds
  safelist: [
    // Add any critical classes that might be purged
    'layout-original',
    'sidebar-sticky',
    'main-content-area',
    'card-content-constrained',
    'entry-content',
    'entry-content.collapsed',
    'entry-content.expanded',
    // Theme and styling modal classes
    'grid-cols-3',
    'max-w-5xl',
    'max-h-[90vh]',
    'overflow-y-auto',
    'p-4',
    'p-6',
    'space-y-4',
    'space-y-6',
    'gap-3',
    'gap-2',
    'rounded-lg',
    'border-2',
    'transition-all',
    'border-blue-500',
    'bg-blue-50',
    'dark:bg-blue-900/20',
    'border-gray-200',
    'dark:border-gray-600',
    'hover:border-gray-300',
    'dark:hover:border-gray-500',
    'text-yellow-600',
    'text-blue-600',
    'text-gray-600',
    'dark:text-gray-400',
    'text-gray-900',
    'dark:text-white',
    'text-xs',
    'font-medium',
    'mx-auto',
    'mb-2',
    'text-center',
    // Portfolio page image classes
    'w-24',
    'h-24',
    'sm:w-28',
    'sm:h-28',
    'lg:w-32',
    'lg:h-32',
    'rounded-full',
    'object-cover',
    'border-4',
    // Responsive text classes
    'text-2xl',
    'sm:text-3xl',
    'lg:text-4xl',
    'text-base',
    'sm:text-lg',
    'lg:text-xl',
    'text-lg',
    'sm:text-xl',
    'text-sm',
    'sm:text-base',
    'text-xs',
    'sm:text-sm',
    // Layout classes
    'min-h-screen',
    'py-6',
    'px-4',
    'sm:py-8',
    'sm:px-6',
    'lg:py-12',
    'lg:px-8',
    'max-w-4xl',
    'mx-auto',
    'mb-8',
    'sm:mb-12',
    'mb-4',
    'sm:mb-6',
    'mb-2',
    'sm:mb-4',
    'space-y-6',
    'sm:space-y-8',
    'px-4',
    'sm:px-6',
    'flex',
    'justify-center',
    'gap-4',
    'sm:gap-6',
    'flex-col',
    'sm:flex-row',
    'gap-3',
    'sm:gap-4',
    'w-full',
    'sm:w-auto',
    'hover:opacity-75',
    'transition-opacity',
    // Card classes
    'border-l-4',
    'pl-3',
    'sm:pl-4',
    'font-semibold',
    'font-medium',
    'mt-2',
    'flex-wrap',
    'gap-2',
    'sm:gap-3',
    'px-2',
    'py-1',
    'sm:px-3',
    'sm:py-1',
    'rounded-full',
    'text-xs',
    'sm:text-sm',
    'ml-1'
  ]
}
